export const DUMMY_DECISIONS = [
  {
    id: "1",
    asset: "Infosys",
    type: "Stock",
    date: "12 Apr",
    thesis: "Strong Q3, margins improving, management guided for strong FY25...",
    confidence: 8,
    emotion: "😌 Calm",
    status: "Reviewed",
    outcome: "+12.4%",
    isPositive: true,
  },
  {
    id: "2",
    asset: "Nifty BeES",
    type: "MF",
    date: "10 Apr",
    thesis: "Market dip, good entry point for long term SIP...",
    confidence: 7,
    emotion: "😤 Excited",
    status: "Pending Review",
    outcome: "—",
    isPositive: null,
  },
  {
    id: "3",
    asset: "Bitcoin",
    type: "Crypto",
    date: "08 Apr",
    thesis: "Halving cycle, institutional buying pressure from ETFs...",
    confidence: 6,
    emotion: "😱 FOMO",
    status: "Open",
    outcome: "—",
    isPositive: null,
  },
  {
    id: "4",
    asset: "HDFC Bank",
    type: "Stock",
    date: "05 Apr",
    thesis: "Undervalued post correction, credit growth still strong...",
    confidence: 9,
    emotion: "😌 Calm",
    status: "Reviewed",
    outcome: "+8.2%",
    isPositive: true,
  },
  {
    id: "5",
    asset: "Tata Motors",
    type: "Stock",
    date: "02 Apr",
    thesis: "EV play, long term thesis but market might correct soon...",
    confidence: 5,
    emotion: "😕 Uncertain",
    status: "Reviewed",
    outcome: "-6.1%",
    isPositive: false,
  },
];

export const USER_STATS = {
  totalDecisions: 47,
  winRate: 64,
  streak: 12,
  logicScore: 71,
};
